### ISSUE TITLE
Will it be possible to make works on OpenShift

### ISSUE THREAD

**Issue by damithkothalawala** [dmuth/facebook-group-stats#4]
Will it be possible to make works on OpenShift ?. 

You may have to use PORT/IP from process.env.OPENSHIFT_NODEJS_PORT &  process.env.OPENSHIFT_NODEJS_IP

**Comment by dmuth** [comment]
Hmm.  I'm hesitant to encode anything that's specific to certain product, but I can think of a couple of workarounds for the port here:

- I could have it honor process.env.PORT instead
- I could use the `config` module and allow the port it listens on to be configure
- You could use nginx or another proxy on your end (this would take the most work, but just throwing it out...)

Let me know if you have a preference for any of the above.


Regarding the IP, I'm not clear on why that would be an issue--this should be listening on all IPs on the machine.  Is that not the case with you?

Thanks,

-- Doug

**Comment by damithkothalawala** [comment]
Hi Doug,

Both process.env.PORT and config option would help. IP is for just technical use only since it could use port redirection via IPtables or other method.

So better if you could make it SAAS compatible regardless of the platform it runs (ex. Heroku / OpenShift / AWS Beanstalk )

Thank You.

**Comment by dmuth** [comment]
Looks like it already supports that, from `bin/www`:

> `var port = normalizePort(process.env.PORT || '3000');`

I verified this by running `PORT=3001 npm start` on the command line and verified that it was listening on port 3001.

Gonna mark this one closed, because it looks like it was checking the PORT variable all along. :-)

-- Doug
